-- 코드를 입력하세요
# SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES*B.PRICE) AS TOTAL_SALES
# FROM BOOK_SALES AS BS
# JOIN BOOK AS B ON BS.BOOK_ID = B.BOOK_ID
# JOIN AUTHOR AS A ON A.AUTHOR_ID = B.AUTHOR_ID
# WHERE YEAR(B.PUBLISHED_DATE) = 2022 AND MONTH(B.PUBLISHED_DATE) = 1
# GROUP BY A.AUTHOR_ID, B.CATEGORY
# ORDER BY A.AUTHOR_ID ASC, CATEGORY DESC

SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM((SALES * PRICE)) AS TOTAL_SALES
FROM BOOK_SALES S
JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY A.AUTHOR_ID, CATEGORY DESC
